name = "MyExample"
uuid = "a82c289b-3bbc-4c9a-9925-9d01ace46859"
authors = ["Bhavesh Shrimali"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
